# Generated by Django 2.1.7 on 2019-03-19 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flight", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="flight", name="arrival", field=models.DateTimeField()
        ),
        migrations.AlterField(
            model_name="flight",
            name="departure",
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
