# Generated by Django 2.1.7 on 2019-03-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_auto_20190320_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='capacity',
            field=models.IntegerField(default=10),
        ),
    ]
