language: python

python:
  - "3.6.5"

services: postgresql

addons:
  postgresql: "9.4"

env:
  - DJANGO=2.1

before_install:
  - export DJANGO_SETTINGS_MODULE=bookings.settings
  - export PYTHONPATH=$HOME/builds/zachang/jirgin
  - export PIP_USE_MIRRORS=true

install:
  - make pip-install
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE jirgin;" -U postgres
  - make migrations
  - make migrate

# command to run tests
script:
  - make test