# Generated by Django 2.1.7 on 2019-03-19 23:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_auto_20190319_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
