# Generated by Django 2.1.7 on 2019-03-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_auto_20190320_0931'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together={('departure', 'fly_from')},
        ),
    ]
