# Generated by Django 2.1.7 on 2019-04-20 21:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("authentication", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default="", max_length=255, verbose_name="image"
            ),
        )
    ]
