# Generated by Django 2.1.7 on 2019-03-19 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_class', models.CharField(choices=[('BUSINESS', 'B'), ('ECONOMY', 'E'), ('FIRST', 'F')], default='ECONOMY', max_length=8)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='flight.Flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('user', 'flight')},
        ),
    ]
